-- 001_esquema.sql: tablas de Origen Café.
-- Se corre una sola vez en Supabase (SQL Editor). Los montos son pesos enteros (sin centavos).

-- Productos: cafés y accesorios en la misma tabla. Los campos de café quedan en null en los accesorios.
create table public.productos (
  id bigint generated by default as identity primary key,
  categoria text not null check (categoria in ('cafe', 'accesorio')),
  nombre text not null check (char_length(nombre) between 2 and 80),
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  descripcion text not null,
  descripcion_corta text,
  imagen_url text,
  activo boolean not null default true,
  created_at timestamptz not null default now(),

  -- Solo cafés
  origen text,
  region text,
  altura text,
  proceso text,
  variedad text,
  perfil text check (perfil in ('frutal', 'equilibrado', 'intenso')),
  tostado text check (tostado in ('claro', 'medio', 'medio-oscuro', 'oscuro')),
  acidez smallint check (acidez between 1 and 5),
  cuerpo smallint check (cuerpo between 1 and 5),
  notas text[] not null default '{}',

  -- Solo accesorios
  beneficios text[] not null default '{}',
  especificaciones jsonb not null default '[]',

  -- Un café tiene que tener sus datos de sabor completos
  constraint cafe_completo check (
    categoria <> 'cafe'
    or (origen is not null and perfil is not null and tostado is not null and acidez is not null and cuerpo is not null)
  )
);

-- Variantes: cada café tiene una por peso; cada accesorio, una sola. Precio y stock propios.
create table public.variantes (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.productos (id) on delete cascade,
  nombre text not null,
  peso_gramos integer check (peso_gramos > 0),
  precio integer not null check (precio >= 0),
  stock integer not null default 0 check (stock >= 0),
  created_at timestamptz not null default now()
);
create index variantes_producto_idx on public.variantes (producto_id);

-- Reseñas de cada producto (datos de ejemplo en el seed)
create table public.resenas (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.productos (id) on delete cascade,
  autor text not null,
  puntaje smallint not null check (puntaje between 1 and 5),
  texto text not null,
  created_at timestamptz not null default now()
);
create index resenas_producto_idx on public.resenas (producto_id);

-- Perfil de cada usuario registrado (auth.users lo maneja Supabase Auth)
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  nombre text,
  role text not null default 'cliente' check (role in ('cliente', 'admin')),
  created_at timestamptz not null default now()
);

-- Órdenes y sus ítems (se usan en E6, con Mercado Pago)
create table public.ordenes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'pagada', 'rechazada', 'cancelada')),
  total integer not null check (total >= 0),
  mp_preference_id text,
  mp_payment_id text,
  created_at timestamptz not null default now()
);
create index ordenes_user_idx on public.ordenes (user_id);

create table public.orden_items (
  id bigint generated by default as identity primary key,
  orden_id bigint not null references public.ordenes (id) on delete cascade,
  variante_id bigint not null references public.variantes (id),
  molienda text check (molienda in ('grano entero', 'fina', 'media-fina', 'media', 'gruesa')),
  cantidad integer not null check (cantidad > 0),
  precio_unitario integer not null check (precio_unitario >= 0)
);
create index orden_items_orden_idx on public.orden_items (orden_id);

-- Cuando alguien se registra, se crea su perfil con rol "cliente".
-- security definer: la función corre con permisos del dueño, porque el usuario recién creado
-- todavía no tiene permiso para escribir en profiles.
create function public.crear_perfil()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, nombre)
  values (new.id, new.raw_user_meta_data ->> 'nombre');
  return new;
end;
$$;

create trigger al_crear_usuario
  after insert on auth.users
  for each row execute function public.crear_perfil();
